/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API.
 * You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"os"

	"github.com/jakule/codersranktask/internal"
	"github.com/joho/godotenv"
)

//go:generate mockgen -source=internal/storage/storage.go -destination internal/mocks/storage_mock.go -package=mocks

func main() {
	err := godotenv.Load()
	if err != nil {
		log.Fatal(err)
	}

	a := internal.App{}
	a.Init(os.Getenv("DATABASE_URL"))
	a.Run(os.Getenv("PORT"))
}
